obj-m			:= iusb.o
iusb-objs		:= iusb-scsi.o iusb-hdisk.o iusb-cdrom.o iusb-vendor.o iusb-hid.o

ccflags-y		:= -I$(srctree)/arch/arm/plat-aspeed/helper -I$(srctree)/arch/arm/plat-aspeed/usbe
ccflags-m		:= -I$(srctree)/arch/arm/plat-aspeed/helper -I$(srctree)/arch/arm/plat-aspeed/usbe
