obj-m := usb1_hw.o
usb1_hw-objs := ast_usbhub.o
ccflags-y		:= -I$(srctree)/arch/arm/plat-aspeed/helper -I$(srctree)/arch/arm/plat-aspeed/usbe
ccflags-m		:= -I$(srctree)/arch/arm/plat-aspeed/helper -I$(srctree)/arch/arm/plat-aspeed/usbe
