obj-m			:= vhid.o
vhid-objs		:= hid_mod.o keybd.o mouse.o

ccflags-y		:= -I$(srctree)/arch/arm/plat-aspeed/helper -I$(srctree)/arch/arm/plat-aspeed/usbe -I$(srctree)/arch/arm/plat-aspeed/iusb
ccflags-m		:= -I$(srctree)/arch/arm/plat-aspeed/helper -I$(srctree)/arch/arm/plat-aspeed/usbe -I$(srctree)/arch/arm/plat-aspeed/iusb

