obj-m			:= usbe.o
usbe-objs		:= mod_reg.o coreusb.o descriptors.o setup.o entry.o bot.o proc.o driver.o linux.o module.o
ccflags-y		:= -I$(srctree)/arch/arm/plat-aspeed/helper
ccflags-m		:= -I$(srctree)/arch/arm/plat-aspeed/helper
